github.csnzoo.com:
    git_protocol: ssh
    users:
        ec825m:
    user: ec825m
github.com:
    git_protocol: ssh
    users:
        eric-chapdelaine:
        ec825m_wayfair:
    user: ec825m_wayfair
